### ISSUE TITLE
add icon in pages and chapters

### ISSUE THREAD

**Issue by warleypo** [klebermachado/BookStack#3]
**Add icon**
![image](https://user-images.githubusercontent.com/50621796/68026638-0cfde700-fc8f-11e9-81fc-c3b5b88ba19d.png)

![image](https://user-images.githubusercontent.com/50621796/68026660-171fe580-fc8f-11e9-8288-2ba2487db01d.png)

**Comment by klebermachado** [comment]
![image](https://user-images.githubusercontent.com/11875260/68242145-c1c93880-ffee-11e9-8e05-144a85585d98.png)

**Comment by klebermachado** [comment]
![image](https://user-images.githubusercontent.com/11875260/68389278-5479ec80-0141-11ea-8456-c22660ec53e3.png)

**Comment by klebermachado** [comment]
Issue:
Icon is being recorded only when updating a chapter

Solution:
Implement image upload also in chapter creation
